[template]
  [template.environment]
    FONT_AWESOME_TOKEN="Your fontawesome token here"

[build]
  command = "yarn build"
  functions = "lambda"
  publish="build"

[dev]
  command = "yarn start"
  port = 3000
  publish = "build"
  functionsPort = 9000

[production]
  command = "yarn build"
  publish = "build"
